name: flutter_fuelet_contracts
description: Flutter Plugin for Fuelet Sway contracts
version: 0.0.5+1
homepage: https://github.com/Fuelet/fuelet_contracts/tree/main/packages/flutter_fuelet_contracts

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  fuelet_contracts: ^1.3.1
  js: ^0.6.5
dev_dependencies:
  flutter_lints: ^2.0.0
  ffi: ^2.0.1
  ffigen: ^7.2.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_fuelet_contracts/js/token_contract.js
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      web:
        pluginClass: JsScriptInjector
        fileName: js_script_injector.dart
