/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TokenContractAbi } from "./TokenContractAbi";

export { TokenContractAbi__factory } from "./factories/TokenContractAbi__factory";
