/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.60.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

export type { TokenContractAbi } from './TokenContractAbi';

export { TokenContractAbi__factory } from './factories/TokenContractAbi__factory';
