[package]
name = "fuelet_contracts"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.61.*"

[dependencies]
flutter_rust_bridge = "1.61.*"
