[package]
name = "fuelet_contracts"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "=1.75.3"

[dependencies]
flutter_rust_bridge = "=1.75.3"
fuels = "0.49.0"
fuels-accounts = "0.49.0" # must be compatible with the fuels version
tokio = { version = "1.14.0", features = ["rt-multi-thread"] }
