[project]
authors = ["Mikhail Poplavkov"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
src_20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.2" }
src_7 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.2" }
