[project]
authors = ["Mikhail Poplavkov"]
entry = "single_asset.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
src_20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.1" }
